version: '3.8'
services:
  database:
    build: 
      context: .
      dockerfile: Dockerfile
      target: database
    ports:
      - "5432:5432"
    volumes:
      - "db-test:/var/lib/postgres/data"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db-test
      TZ: "Asia/Tokyo"
volumes:
  db-test: